In [1]:
!pip install -q -U transformers datasets accelerate peft boto3

import os, boto3, torch
from google.colab import userdata
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from peft import LoraConfig, get_peft_model

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 135.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 44.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.3/394.3 kB 33.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 126.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 11.1 MB/s eta 0:00:00

In [2]:
!pip install -U torchao
import torch
import torchao
import peft

Requirement already satisfied: torchao in /usr/local/lib/python3.13/dist-packages (0.10.0)
Collecting torchao
  Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (21 kB)
Downloading torchao-0.18.0-cp310-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 104.6 MB/s eta 0:00:00
Installing collected packages: torchao
  Attempting uninstall: torchao
    Found existing installation: torchao 0.10.0
    Uninstalling torchao-0.10.0:
      Successfully uninstalled torchao-0.10.0
Successfully installed torchao-0.18.0

WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_mxfp8.cpython-310-x86_64-linux-gnu.so
WARNING:torchao:Failed to load /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so: Could not load this library: /usr/local/lib/python3.13/dist-packages/torchao/_C_cutlass_90a.abi3.so

In [3]:
BUCKET = "legai-ai-embeddings"
MODEL_NAME = "Qwen/Qwen2.5-3B-Instruct"

TRAIN_KEY = "finetune/legal_rag_train.jsonl"
VAL_KEY = "finetune/legal_rag_validation.jsonl"

TRAIN_FILE = "/content/legal_rag_train.jsonl"
VAL_FILE = "/content/legal_rag_validation.jsonl"
OUTPUT_DIR = "/content/legai_lora"

s3 = boto3.client("s3", aws_access_key_id=userdata.get("AWS_ACCESS_KEY_ID"), aws_secret_access_key=userdata.get("AWS_SECRET_ACCESS_KEY"), region_name="us-east-1")

In [5]:
# import boto3
# from getpass import getpass

# AWS_ACCESS_KEY_ID = input("AWS Access Key ID: ")
# AWS_SECRET_ACCESS_KEY = getpass("AWS Secret Access Key: ")
# AWS_REGION = input("AWS Region (example: us-east-1): ")

# s3 = boto3.client(
#     "s3",
#     aws_access_key_id=AWS_ACCESS_KEY_ID,
#     aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
#     region_name=AWS_REGION
# )

AWS Access Key ID: AKIAR47L3GKLNZNZUXNO
AWS Secret Access Key: ··········
AWS Region (example: us-east-1): us-east-1

In [ ]:
# sts = boto3.client(
#     "sts",
#     aws_access_key_id=AWS_ACCESS_KEY_ID,
#     aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
#     region_name=AWS_REGION
# )

# print(sts.get_caller_identity())

In [7]:
s3.download_file(BUCKET, TRAIN_KEY, TRAIN_FILE)
s3.download_file(BUCKET, VAL_KEY, VAL_FILE)

dataset = load_dataset("json", data_files={"train": TRAIN_FILE, "validation": VAL_FILE})

print(dataset)

Generating train split: 0 examples [00:00, ? examples/s]

Generating validation split: 0 examples [00:00, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['vector_id', 'source', 'context', 'question', 'answer'],
        num_rows: 4611
    })
    validation: Dataset({
        features: ['vector_id', 'source', 'context', 'question', 'answer'],
        num_rows: 243
    })
})

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

In [9]:
SYSTEM = "You are LegaiAI, a legal information assistant. Answer the question using only the provided legal context. Do not invent facts, laws, cases, or citations."

In [10]:
def tokenize_example(x):
    prompt_messages = [
        {"role": "system", "content": SYSTEM},
        {"role": "user", "content": f"LEGAL CONTEXT:\n{x['context']}\n\nQUESTION:\n{x['question']}"}
    ]

    full_messages = prompt_messages + [{"role": "assistant", "content": x["answer"]}]

    prompt_text = tokenizer.apply_chat_template(prompt_messages, tokenize=False, add_generation_prompt=True)
    full_text = tokenizer.apply_chat_template(full_messages, tokenize=False, add_generation_prompt=False)

    full = tokenizer(full_text, truncation=True, max_length=2048, add_special_tokens=False)
    prompt = tokenizer(prompt_text, truncation=True, max_length=2048, add_special_tokens=False)

    labels = full["input_ids"].copy()
    prompt_length = min(len(prompt["input_ids"]), len(labels))
    labels[:prompt_length] = [-100] * prompt_length

    full["labels"] = labels

    return full

In [11]:
train_ds = dataset["train"].map(tokenize_example, remove_columns=dataset["train"].column_names, num_proc=4)
val_ds = dataset["validation"].map(tokenize_example, remove_columns=dataset["validation"].column_names, num_proc=4)

Map (num_proc=4):   0%|          | 0/4611 [00:00<?, ? examples/s]

Map (num_proc=4):   0%|          | 0/243 [00:00<?, ? examples/s]

In [12]:
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.bfloat16, device_map="auto")
model.config.use_cache = False

[transformers] `torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors.index.json:   0%|          | 0.00/35.6k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/434 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

In [13]:
!nvidia-smi

Tue Sep 15 01:02:35 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100-SXM4-80GB          Off |   00000000:00:05.0 Off |                    0 |
| N/A   32C    P0             61W /  400W |    6386MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            1537      C   /usr/bin/python3                       6374MiB |
+-----------------------------------------------------------------------------------------+

In [14]:
lora = LoraConfig(r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM", target_modules="all-linear")

model = get_peft_model(model, lora)
model.print_trainable_parameters()

trainable params: 29,933,568 || all params: 3,115,872,256 || trainable%: 0.9607

In [15]:
args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=2,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    bf16=True,
    logging_steps=10,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    save_total_limit=3,
    load_best_model_at_end=True,
    report_to="none"
)

In [16]:
from torch.nn.utils.rnn import pad_sequence

def collator(features):
    input_ids = [torch.tensor(x["input_ids"], dtype=torch.long) for x in features]
    attention_mask = [torch.tensor(x["attention_mask"], dtype=torch.long) for x in features]
    labels = [torch.tensor(x["labels"], dtype=torch.long) for x in features]

    return {
        "input_ids": pad_sequence(input_ids, batch_first=True, padding_value=tokenizer.pad_token_id),
        "attention_mask": pad_sequence(attention_mask, batch_first=True, padding_value=0),
        "labels": pad_sequence(labels, batch_first=True, padding_value=-100)
    }

In [17]:
test_batch = collator([train_ds[0], train_ds[1], train_ds[2], train_ds[3]])

print("input_ids:", test_batch["input_ids"].shape)
print("attention_mask:", test_batch["attention_mask"].shape)
print("labels:", test_batch["labels"].shape)

input_ids: torch.Size([4, 1734])
attention_mask: torch.Size([4, 1734])
labels: torch.Size([4, 1734])

In [18]:
trainer = Trainer(model=model, args=args, train_dataset=train_ds, eval_dataset=val_ds, data_collator=collator)

trainer.train()

TrainOutput(global_step=578, training_loss=0.09897789163160489, metrics={'train_runtime': 2048.1928, 'train_samples_per_second': 4.503, 'train_steps_per_second': 0.282, 'total_flos': 1.9460440479552307e+17, 'train_loss': 0.09897789163160489, 'epoch': 2.0})

In [19]:
results = trainer.evaluate()
print(results)

{'eval_loss': 0.1357056051492691}

In [20]:
FINAL_DIR = "/content/legai_final_adapter"

model.save_pretrained(FINAL_DIR)
tokenizer.save_pretrained(FINAL_DIR)

('/content/legai_final_adapter/tokenizer_config.json',
 '/content/legai_final_adapter/chat_template.jinja',
 '/content/legai_final_adapter/tokenizer.json')

In [21]:
for root, _, files in os.walk(FINAL_DIR):
    for file in files:
        local = os.path.join(root, file)
        relative = os.path.relpath(local, FINAL_DIR).replace("\\", "/")
        s3.upload_file(local, BUCKET, f"finetune/final_adapter/{relative}")

print("Fine-tuned LegaiAI adapter uploaded.")

Fine-tuned LegaiAI adapter uploaded.